// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYkdUOqZTlzr33QxNvnrVAfywTrANYH4',
    appId: '1:385330183189:ios:b593184b2d54a06b48a21c',
    messagingSenderId: '385330183189',
    projectId: 'travelink-49b5b',
    storageBucket: 'travelink-49b5b.firebasestorage.app',
    iosBundleId: 'com.example.travelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYkdUOqZTlzr33QxNvnrVAfywTrANYH4',
    appId: '1:385330183189:ios:b593184b2d54a06b48a21c',
    messagingSenderId: '385330183189',
    projectId: 'travelink-49b5b',
    storageBucket: 'travelink-49b5b.firebasestorage.app',
    iosBundleId: 'com.example.travelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Tq7Gdi75QHm7buirkVCPQ_WTsQSv5Qw',
    appId: '1:385330183189:web:184c4683247aed4948a21c',
    messagingSenderId: '385330183189',
    projectId: 'travelink-49b5b',
    authDomain: 'travelink-49b5b.firebaseapp.com',
    storageBucket: 'travelink-49b5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-w9-2Pe5vqZunF0U_BEExvtlGMhD65IQ',
    appId: '1:385330183189:android:bcb56c3cf2011eb948a21c',
    messagingSenderId: '385330183189',
    projectId: 'travelink-49b5b',
    storageBucket: 'travelink-49b5b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Tq7Gdi75QHm7buirkVCPQ_WTsQSv5Qw',
    appId: '1:385330183189:web:184c4683247aed4948a21c',
    messagingSenderId: '385330183189',
    projectId: 'travelink-49b5b',
    authDomain: 'travelink-49b5b.firebaseapp.com',
    storageBucket: 'travelink-49b5b.firebasestorage.app',
  );

}